export enum weapon_type {
  AK47 = 'AK-47',
  M4A4 = 'M4A4',
  M4A1S = 'M4A1-S',
  AWP = 'AWP',
  SSG08 = 'SSG 08',
  AUG = 'AUG',
  SG553 = 'SG 553',
  FAMAS = 'FAMAS',
  GALIL_AR = 'Galil AR',

  // SMGs
  MAC10 = 'MAC-10',
  MP5SD = 'MP5-SD',
  MP7 = 'MP7',
  MP9 = 'MP9',
  P90 = 'P90',
  PPBIZON = 'PP-Bizon',
  UMP45 = 'UMP-45',

  // Rifles (Shotguns, Snipers, Heavy)
  SCAR20 = 'SCAR-20',
  G3SG1 = 'G3SG1',
  NOVA = 'Nova',
  XM1014 = 'XM1014',
  MAG7 = 'MAG-7',
  SAWEDOFF = 'Sawed-Off',
  M249 = 'M249',
  NEGEV = 'Negev',

  // Pistols
  GLOCK18 = 'Glock-18',
  USP_S = 'USP-S',
  P2000 = 'P2000',
  P250 = 'P250',
  FIVESEVEN = 'Five-SeveN',
  TEC9 = 'Tec-9',
  CZ75 = 'CZ75-Auto',
  DUAL_BERETTAS = 'Dual Berettas',
  DEAGLE = 'Desert Eagle',
  R8 = 'R8 Revolver',

  // Knives (generics — skins apply over base)
  BAYONET = 'Bayonet',
  KARAMBIT = 'Karambit',
  M9_BAYONET = 'M9 Bayonet',
  BUTTERFLY = 'Butterfly Knife',
  FALCHION = 'Falchion Knife',
  HUNTSMAN = 'Huntsman Knife',
  SHADOW_DAGGERS = 'Shadow Daggers',
  BOWIE = 'Bowie Knife',
  CLASSIC = 'Classic Knife',
  NOMAD = 'Nomad Knife',
  SURVIVAL = 'Survival Knife',
  STILETTO = 'Stiletto Knife',
  TACTICAL = 'Tactical Knife',
  PARACORD = 'Paracord Knife',
  TALON = 'Talon Knife',
}